bandoteca/config/routes.rb
Rails.application.routes.draw do

  devise_for :users , controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords"
}

  resources :genres
  resources :bands
  resources :reservations
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "welcome#index"
end

bandoteca/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bandoteca/app/models/band.rb
class Band < ApplicationRecord
  belongs_to :genre
  has_many :reservations

end

bandoteca/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

bandoteca/app/models/genre.rb
class Genre < ApplicationRecord
  has_many :bands
end

bandoteca/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :band
  belongs_to :user
end

bandoteca/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reservations
  has_many :comments
end

bandoteca/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

bandoteca/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
    @genres = Genre.all
  end

  def create
    @band = Band.create(band_params)

    @band.save
    redirect_to genre_path(@band.genre_id)
  end

  private

  def band_params
    params.require(:band).permit(:name, :price, :rate, :image_url, :review, :genre_id)
  end
end

bandoteca/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to comments_path
    else
      render 'root_path'
    end
  end

  def new
    @comment = Comment.new
  end

  def index
    @comments = Comment.all
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to comments_path
    else
      render 'edit'
    end
  end


private

  def comment_params
    params.require(:comment).permit(:user_id, :comment)
  end

end

bandoteca/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.create(genre_params)

    @genre.save
    redirect_to root_path
  end

  def show
    @genre = Genre.find(params[:id])
    @bands = @genre.bands
    @reservations = Reservation.new
  end

  private

  def genre_params
    params.require(:genre).permit(:name_genre, :image_url_genre)
  end
end

bandoteca/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = current_user.reservations
  end

  def create
    @reservation = Reservation.create(reservation_params)

    @reservation.save
    redirect_to reservations_path
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @band = @reservation.band.genre_id
    @reservation.destroy
    redirect_to genre_path(@band)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date, :band_id, :user_id)
  end
end

bandoteca/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

bandoteca/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

bandoteca/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

bandoteca/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

bandoteca/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

bandoteca/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @genres = Genre.all
  end

  def create
  end
end

bandoteca/app/helpers/application_helper.rb
module ApplicationHelper
end

bandoteca/app/helpers/bands_helper.rb
module BandsHelper
end

bandoteca/app/helpers/comments_helper.rb
module CommentsHelper
end

bandoteca/app/helpers/genres_helper.rb
module GenresHelper
end

bandoteca/app/helpers/reservations_helper.rb
module ReservationsHelper
end

bandoteca/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bandoteca/app/views/bands/new.html.erb
<%= form_for @band, url: {action: "create"} do |f| %>
  <p>
    <%= f.label :name, class:"new_band" %><br>
    <%= f.text_field :name, class:"new_band_field" %>
  </p>

  <p>
    <%= f.label :price, class:"new_band" %><br>
    <%= f.text_field :price, class:"new_band_field" %>
  </p>

  <p>
    <%= f.label :image_url, class:"new_band" %><br>
    <%= f.text_field :image_url, class:"new_band_field" %>
  </p>

  <p>
    <%= f.label :review, class:"new_band" %><br>
    <%= f.text_field :review, class:"new_band_field" %>
  </p><br>

  <p class="create_band">
  <%= f.select "genre_id", options_from_collection_for_select(@genres, "id", "name_genre") %>
  </p>
  <p>
    <%= f.submit class:"create_band"%>
  </p>

<% end %>

bandoteca/app/views/comments/edit.html.erb
<%= form_for @comment, url: {action: "update"} do |f| %>
<p>
  <%= f.label :comment %>
  <%= f.text_area :comment %><br>
  <%= f.submit %>
</p>
<% end %>

bandoteca/app/views/comments/index.html.erb
<div class="lgv3">
<h2>
  The page has <%= pluralize(@comments.count, "comments") %>
</h2>

<% @comments.each do |comment|%>

<p>
  <b><%= comment.user.email %></b>
</p>

<p>
  <i><%= comment.created_at %></i>
</p>

<p>
  <i><%= comment.updated_at %></i>
</p>

<p><%= comment.comment %></p>

<li class="logout btn btn-info">
  <%= link_to 'New Comment', new_comment_path %>
</li>

  <% if current_user.admin %>
    <li class="logout btn btn-info">
      <%= link_to 'Delete Comment', comment_path(comment), method: :delete %>
    </li>

    <li class="logout btn btn-info">
      <%= link_to 'Edit Comment', edit_comment_path(comment) %>
    </li>
  <% end %>
<% end %>
</div>

bandoteca/app/views/comments/new.html.erb
<%= form_for @comment, url: {action: "create"} do |f| %>
<p>
  <%= f.text_area :comment %><br>
  <%= f.submit %>
</p>
<% end %>

bandoteca/app/views/genres/new.html.erb
<%= form_for @genre, url: {action: "create"} do |f| %>
  <p>
    <%= f.label :name_genre %><br>
    <%= f.text_field :name_genre %>
  </p>

  <p>
    <%= f.label :image_url_genre %><br>
    <%= f.text_field :image_url_genre %>
  </p>

  <p>
    <%= f.submit class:"btn btn-warning"%>
  </p>

<% end %>

bandoteca/app/views/genres/show.html.erb
<div class="lgv">
<h1>Bands</h1>

<% @bands.each do |band| %>

  <img class="img-rounded img-thumbnail" width="200" height="200"
    src="<%= band.image_url %>">
  <ul class="info_band"><br>
    <li>
      <strong> <%= band.name %> </strong>
    </li>
    <li>
      <em> $<%= band.price %> </em>
    </li>
  </ul>
  <p class="review text-justify">
    <medium> <%= band.review %> </medium>
  </p>


<div class="col-xs-12">

  <%= form_for @reservations, url: reservations_path do |f| %>

    <div class="form-group">
      <%= f.label :date, class:"date" %><br>
      <%= f.date_field :date %>
    </div>

      <%= f.hidden_field :user_id, value: current_user.id  %>
      <%= f.hidden_field :band_id, value: band.id%>

    <p>
      <%= f.submit %>
    </p><br>

  <% end %>
<% end %>

<% if current_user.admin %>
  <%= link_to 'bands', new_band_path, class:"admin btn btn-info band" %>
<% end %>
</div>

bandoteca/app/views/reservations/index.html.erb
<div class="lgv2">


<h1>Reservations</h1>

<% @reservations.each do |reservation| %>

<ol class="info_band">
    <li>
      <strong> <%= reservation.date %> </strong>
    </li>
    <li>
      <em> <%= reservation.band.name %> </em>
    </li>
    <li>
      <em> <%= reservation.user.email %> </em>
    </li>
  </ul>
</ol>
</div>

<% if current_user.admin %>
  <%= link_to 'delete', reservation_path(reservation), method: :delete,
      class:"delete btn btn-info" %><br>
  <% end %>
<% end %>