bandoteca/config/routes.rb
Rails.application.routes.draw do

  devise_for :users , controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords"
}

  resources :genres
  resources :bands
  resources :reservations
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "welcome#index"
end

bandoteca/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bandoteca/app/models/band.rb
class Band < ApplicationRecord
  belongs_to :genre
  has_many :reservations

end

bandoteca/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

bandoteca/app/models/genre.rb
class Genre < ApplicationRecord
  has_many :bands
end

bandoteca/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :band
  belongs_to :user
end

bandoteca/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reservations
  has_many :comments
end

bandoteca/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

bandoteca/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
    @genres = Genre.all
  end

  def create
    @band = Band.create(band_params)

    @band.save
    redirect_to genre_path(@band.genre_id)
  end

  private

  def band_params
    params.require(:band).permit(:name, :price, :rate, :image_url, :review, :genre_id)
  end
end

bandoteca/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to comments_path
    else
      render 'root_path'
    end
  end

  def new
    @comment = Comment.new
  end

  def index
    @comments = Comment.all
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to comments_path
    else
      render 'edit'
    end
  end


private

  def comment_params
    params.require(:comment).permit(:user_id, :comment)
  end

end

bandoteca/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.create(genre_params)

    @genre.save
    redirect_to root_path
  end

  def show
    @genre = Genre.find(params[:id])
    @bands = @genre.bands
    @reservations = Reservation.new
  end

  private

  def genre_params
    params.require(:genre).permit(:name_genre, :image_url_genre)
  end
end

bandoteca/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = current_user.reservations
  end

  def create
    @reservation = Reservation.create(reservation_params)

    @reservation.save
    redirect_to reservations_path
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @band = @reservation.band.genre_id
    @reservation.destroy
    redirect_to genre_path(@band)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date, :band_id, :user_id)
  end
end

bandoteca/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

bandoteca/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

bandoteca/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

bandoteca/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

bandoteca/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @genres = Genre.all
  end

  def create
  end
end

bandoteca/app/helpers/application_helper.rb
module ApplicationHelper
end

bandoteca/app/helpers/bands_helper.rb
module BandsHelper
end

bandoteca/app/helpers/comments_helper.rb
module CommentsHelper
end

bandoteca/app/helpers/genres_helper.rb
module GenresHelper
end

bandoteca/app/helpers/reservations_helper.rb
module ReservationsHelper
end

bandoteca/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bandoteca/app/views/welcome/index.html.erb
<div class="container">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div id="my-slider" class="carousel slide" data-ride="carousel">

          <ol class="carousel-indicators">
            <li data-target="#my-slider" data-slide-to="0" class="active"></li>
            <li data-target="#my-slider" data-slide-to="1"></li>
            <li data-target="#my-slider" data-slide-to="2"></li>
          </ol>

          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="https://wallpaperscraft.com/image/metallica_concert_fan_show_light_3663_1920x1080.jpg" alt="metallica">
              <div class="carousel-caption">
                <h1>Welcome</h1>
              </div>
            </div>
            <div class="item">
              <img src="https://pxhst.co/avaxhome/ff/91/004291ff.jpg" alt="acdc">
              <div class="carousel-caption">
                <h1>Enjoy!</h1>
              </div>
            </div>
            <div class="item">
              <img src="http://www.busforfun.com/picture/Immagine/62/original/245a808d3c2fe4cc559e1cca84935745.jpg" alt="iron">
              <div class="carousel-caption">
                <h1>Book your favorite Artist</h1>
              </div>
            </div>
          </div>
          <!--controls-->
          <a class="left carousel-control" href="#my-slider" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true">
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#my-slider" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true">
            </span>
            <span class="sr-only">Previous</span>
          </a>

        </div>
      </div>
    </div>
  </div>
</div>

  <div id="results">
    <%= form_tag root_path, :method => 'get' do %>
    <%= text_field_tag :keyword, nil, placeholder: "Que deseas buscar"%>
    <%= submit_tag "search", :name => nil %>
    <% end %>

    <% @genres.each do |genre| %>
    <div class="container-fluid">

      <div class="row col-xs-5 imgs">
        <img class="img-responsive img-circle img-thumbnail" width="200" height="200"
        src="<%= genre.image_url_genre %>"
        alt="Rock"><br>


        <%= link_to genre.name_genre, genre_path(genre),
        class:"genre btn-xs btn btn-primary" %> <br>
        <% end %>
      </div>
    </div>

      <% if current_user.admin %>
      <%= link_to 'genres', new_genre_path,
      class:"admin btn btn-info" %>
      <% end %>